# Copyright (C) 2019 Knot.x Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  workspaceDir: knotx-repos

steps:
  - script: |
      git clone https://github.com/Knotx/knotx-aggregator.git
      mkdir $(workspaceDir)
    displayName: "Prepare Aggregator"
  - task: CmdLine@2
    inputs:
      script: |
        ORGANIZATION=$(cut -d'/' -f1 <<<$(Build.Repository.Name))
        echo "Organization: $ORGANIZATION"
        echo "Build.Repository.Uri: $(Build.Repository.Uri)"
        echo "Build.SourceBranch: $(Build.SourceBranch)"
        echo "Build.Repository.Name: $(Build.Repository.Name)"
        echo "Build.TriggeredBy.ProjectID: $(Build.TriggeredBy.ProjectID)"
        echo "System.PullRequest.SourceRepositoryURI: $(System.PullRequest.SourceRepositoryURI)"
        echo "System.PullRequest.SourceBranch: $(System.PullRequest.SourceBranch)"
        echo "System.PullRequest.TargetBranch: $(System.PullRequest.TargetBranch)"
        echo "System.TeamProject: $(System.TeamProject)"
        cd knotx-aggregator/development
        if [[ -z "$(System.PullRequest.SourceBranch)" ]] ; then
          ./pull-all.sh -r ../../$(workspaceDir) -b "$(Build.SourceBranchName)" -a -o $ORGANIZATION
        else
          ./pull-all.sh -r ../../$(workspaceDir) -b $(System.PullRequest.SourceBranch) -a -o $ORGANIZATION
        fi
    displayName: "Clone all repositories"